# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: '5ed02d7a-76a4-41df-a3cb-f64aab9d71ee'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'testgp'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateWebApp/azuredeploy.json'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'

